name: Lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install requirements
        run: python3 -m pip install ruff==0.11.6 homeassistant>=2024.12.0

      - name: Lint
        run: python3 -m ruff check .

      - name: Format
        run: python3 -m ruff format . --check